### ISSUE TITLE
Constant 409 update in progress bug

### ISSUE THREAD

**Issue by maurocasas** [hammerstonedev/sidecar#32] opened 2021-09-24 18:19 UTC
We're facing a very strange issue which is constantly breaking out deploys.

We have to manually delete all the Lambda's before trying to deploy, otherwise we encounter the following:

```
Error executing "UpdateFunctionCode" on "https://lambda.***.amazona  
  ws.com/2015-03-31/functions/SC-Appname-staging-Sidecar-Dacast-CreateLivestrea  
  m/code"; AWS HTTP error: Client error: `PUT https://lambda.***.amazon  
  aws.com/2015-03-31/functions/SC-Appname-staging-Sidecar-Dacast-CreateLivestre  
  am/code` resulted in a `409 Conflict` response:                              
  {"Type":"User","message":"The operation cannot be performed at this time. A  
  n update is in progress for resource: arn:aws (truncated...)                 
   ResourceConflictException (client): The operation cannot be performed at t  
  his time. An update is in progress for resource: arn:aws:lambda:***:6  
  88009524528:function:SC-Appname-staging-Sidecar-Dacast-CreateLivestream - {"T  
  ype":"User","message":"The operation cannot be performed at this time. An u  
  pdate is in progress for resource: arn:aws:lambda:***:688009524528:fu  
  nction:SC-Appname-staging-Sidecar-Dacast-CreateLivestream"}   
```

We're a bit lost here, is there anything we're doing wrong? We have changed our Sidecar implementation in the last 3 months, it just started happening 4 days ago and it's becoming a hair puller.

Any guidance?

**Comment by aarondfrancis** [comment] 2021-09-24 19:36
Hm this is strange indeed. 

After you manually delete all the lambdas, I assume it works one time and then fails for subsequent events?

Let me look into it.

**Comment by aarondfrancis** [comment] 2021-09-24 19:39
Are you deploying an image or using a native runtime?

**Comment by aarondfrancis** [comment] 2021-09-24 19:45
Ok final question. Can you show me the full output from the CLI so I see what step it's happening at? E.g. something like this:

```
[Sidecar] Deploying App\Sidecar\OgImage to Lambda as `SC-Laravel-local-Sidecar-OgImage`.
          ↳ Environment: local
          ↳ Package Type: Zip
          ↳ Runtime: nodejs12.x
          ↳ Function already exists, potentially updating code and configuration.
          ↳ Packaging files for deployment.
          ↳ Package unchanged. Reusing s3://sidecar-us-east-2-1622652312/sidecar/001-1dc8db01d90faae78c441d7dd26677b5.zip.
          ↳ Function code and configuration updated.
          ↳ Removing outdated version 76.
[Sidecar] Activating function App\Sidecar\OgImage.
          ↳ Updating environment variables.
          ↳ Activating Version 96 of SC-Laravel-local-Sidecar-OgImage.
```

**Comment by gera919** [comment] 2021-09-24 20:37
Hey @aarondfrancis thanks for attending this, this is the log:

```
[Sidecar] Deploying App\Sidecar\Dacast\CreateLivestream to Lambda as `SC-Embark-canary-Sidecar-Dacast-CreateLivestream`.
          ↳ Environment: canary
          ↳ Package Type: Zip
          ↳ Runtime: nodejs14.x
          ↳ Function already exists, potentially updating code and configuration.
          ↳ Packaging files for deployment.
          ↳ Package unchanged. Reusing s3://***/sidecar/001-58568760efeee93792cbe81b9295ebea.zip.
          ↳ Function code and configuration are unchanged. Not updating anything.
[Sidecar] Deploying App\Sidecar\Zoom\UpdateLivestreamSettings to Lambda as `SC-Embark-canary-Sidecar-Zoom-UpdateLivestreamSettings`.
          ↳ Environment: canary
          ↳ Package Type: Zip
          ↳ Runtime: nodejs14.x
          ↳ Function already exists, potentially updating code and configuration.
          ↳ Packaging files for deployment.
          ↳ Package unchanged. Reusing s3://***/sidecar/001-58568760efeee93792cbe81b9295ebea.zip.

   Aws\Lambda\Exception\LambdaException 

  Error executing "UpdateFunctionCode" on "https://lambda.***.amazonaws.com/2015-03-31/functions/SC-Embark-canary-Sidecar-Zoom-UpdateLivestreamSettings/code"; AWS HTTP error: Client error: `PUT https://lambda.***.amazonaws.com/2015-03-31/functions/SC-Embark-canary-Sidecar-Zoom-UpdateLivestreamSettings/code` resulted in a `409 Conflict` response:
{"Type":"User","message":"The operation cannot be performed at this time. An update is in progress for resource: arn:aws (truncated...)
 ResourceConflictException (client): The operation cannot be performed at this time. An update is in progress for resource: arn:aws:lambda:***:688009524528:function:SC-Embark-canary-Sidecar-Zoom-UpdateLivestreamSettings - {"Type":"User","message":"The operation cannot be performed at this time. An update is in progress for resource: arn:aws:lambda:***:688009524528:function:SC-Embark-canary-Sidecar-Zoom-UpdateLivestreamSettings"}

  at vendor/aws/aws-sdk-php/src/WrappedHttpHandler.php:195
    191▕         $parts['request'] = $request;
    192▕         $parts['connection_error'] = !empty($err['connection_error']);
    193▕         $parts['transfer_stats'] = $stats;
    194▕ 
  ➜ 195▕         return new $this->exceptionClass(
    196▕             sprintf(
    197▕                 'Error executing "%s" on "%s"; %s',
    198▕                 $command->getName(),
    199▕                 $request->getUri(),

      +41 vendor frames 
  42  artisan:37
      Illuminate\Foundation\Console\Kernel::handle()
```

**Comment by aarondfrancis** [comment] 2021-09-24 21:20
Fascinating. I see that CreateLivestream worked but UpdateLivestreamSettings failed. Is that how it normally goes?

**Comment by aarondfrancis** [comment] 2021-09-24 21:22
Also it looks like the package was unchanged, so it was able to reuse the zip. What _did_ change that caused it to update? Did something change in the function configuration?

**Comment by lovenick** [comment] 2021-09-24 23:17
I've been experience the same issue. To work around, I either delete the lambda or update the name. Currently breaking all deploys via Github Actions. 

As far as I can tell, nothing changed on my end. Due to a mistake, I had to re-configure Sidecar with new AWS keys. Since then, it's been a consistent error. I haven't had a chance to really dive in, but happy to help if I can.

Appreciate the work on this package. It's made my life 1000% easier.

**Comment by aarondfrancis** [comment] 2021-09-25 02:56
Thanks for the input Nick, really sorry this is happening! Can you
similarly post the output from one of the recent failures? And can you post
your Sidecar class as well, whatever parts you can share with me? Thanks!

**Comment by aarondfrancis** [comment] 2021-09-27 02:47
Hey y'all, I haven't been able to replicate it, but I did [add](https://github.com/hammerstonedev/sidecar/commit/0457e91ee5f96b09a480ba29771ff04871290948) a `retry` to see if that fixes it.

Can y'all try `dev-main` and see if that fixes it? And if not, can you paste in the contents of your PHP class so I can dig in further?

**Comment by lovenick** [comment] 2021-09-27 20:25
Sorry for the delay, I've been taking weekends off with the family.

For some reason, deployments work today. No errors, no deleting lambdas and no renaming. I'm going to assume this was some sort of AWS hiccup.

Would you still like the error log from last weeks deploy and Sidecar class for reference?

Also, if there's a way I can support your open source efforts, let me know. Torchlight looks awesome, I just don't have a use for it... yet :D

**Comment by aarondfrancis** [comment] 2021-09-27 20:34
Ha, the AWS gods have relented! 

If you still have the error log hanging around, I'd still love to take a look at it. No worries if not.

> Also, if there's a way I can support your open source efforts, let me know. Torchlight looks awesome, I just don't have a use for it... yet :D

You're kind to say so! No other way for now, but I really appreciate you asking 😄

**Comment by gera919** [comment] 2021-09-27 21:19
@aarondfrancis we just tried again using the `dev-main` version and seems to work fine, we're not sure if this is because your change or because the AWS gods have relented 😄 but it's working now.

We'll do some more test and will keep an eye in case the issue appears again.

Thanks for your help! 👍🏻

**Comment by danatemple** [comment] 2021-10-31 12:50
@aarondfrancis you said you'd like to see this - well I can now produce this error, and this is literally with my very first "hello world" Sidecar tryout, i.e. deploying one .js file. Initially it worked right out of the box - awesome work you guys! - but having edited the file once, all further attempts to deploy seem to fail.

```
[Sidecar] Deploying App\Sidecar\D3UtilsFunction to Lambda as `SC-DDScarlet1-scarlet1-Sidecar-D3UtilsFunction`.
          # Environment: scarlet1
          # Package Type: Zip
          # Runtime: nodejs14.x
          # Function already exists, potentially updating code and configuration.
          # Packaging files for deployment.
          # Creating a new zip file.
          # Zip file created at s3://sidecar-us-east-1-1635678578/sidecar/001-5098b03fb68a8a1a0d069d0e5bf34cfe.zip

   Aws\Lambda\Exception\LambdaException 

  Error executing "UpdateFunctionCode" on "https://lambda.us-east-1.amazonaws.com/2015-03-31/functions/SC-DDScarlet1-scarlet1-Sidecar-D3UtilsFunction/code"; AWS HTTP error: Client error: `PUT https://lambda.us-east-1.amazonaws.com/2015-03-31/functions/SC-DDScarlet1-scarlet1-Sidecar-D3UtilsFunction/code` resulted in a `409 Conflict` response:
{"Type":"User","message":"The operation cannot be performed at this time. An update is in progress for resource: arn:aws (truncated...)
 ResourceConflictException (client): The operation cannot be performed at this time. An update is in progress for resource: arn:aws:lambda:us-east-1:558517226390:function:SC-DDScarlet1-scarlet1-Sidecar-D3UtilsFunction - {"Type":"User","message":"The operation cannot be performed at this time. An update is in progress for resource: arn:aws:lambda:us-east-1:558517226390:function:SC-DDScarlet1-scarlet1-Sidecar-D3UtilsFunction"}

  at vendor/aws/aws-sdk-php/src/WrappedHttpHandler.php:195
    191#         $parts['request'] = $request;
    192#         $parts['connection_error'] = !empty($err['connection_error']);
    193#         $parts['transfer_stats'] = $stats;
    194# 
  # 195#         return new $this->exceptionClass(
    196#             sprintf(
    197#                 'Error executing "%s" on "%s"; %s',

```

The Sidecar class is attached (it is PHP, but GitHub doesn't allow PHP attachments!) - completely boilerplate.

[D3UtilsFunction.txt](https://github.com/hammerstonedev/sidecar/files/7448840/D3UtilsFunction.txt)
 
I have looked at the Lambda GUI on AWS, the only thing I can see is that the "modified" time updates on each attempt, but no new version ever gets created. No visible errors I can find on the UI.

I will open a support case with AWS also.

**Comment by aarondfrancis** [comment] 2021-10-31 19:56
@danatemple thank you for the extra info! Can you try `dev-main` and see if that fixes it? I added a patch in there that is (as of right now) unreleased. I'll release it in a bit probably.

**Comment by danatemple** [comment] 2021-11-01 07:25
Works! I first checked that it was still failing, to be sure AWS hadn't changed anything, then updated and can now deploy new code, no problem.
Should I close my AWS support case (if you've identified a definite root cause) or might there be useful insights from getting them to see what is going wrong?
I have NOT re-deployed the initial function that failed, I kept that untouched so they can still look at it.

**Comment by danatemple** [comment] 2021-11-09 12:43
@aarondfrancis just wondering if you've seen the AWS response above? They imply it is something that recently changed, or might be a race condition?

_"To provide some context, this issue is related to the new Expansion of AWS Lambda states to all functions[1]. This change impacts workflows that attempt to invoke or modify a function shortly after a create or an update action."_

**Comment by danatemple** [comment] 2021-11-19 12:37
@aarondfrancis just hit this again, even though we're still on dev-main.

**Comment by 949mac** [comment] 2021-12-23 01:08
@aarondfrancis --

Hello, I've now experiencing this issue today too.

**Comment by jeffreyvanhees** [comment] 2021-12-28 15:31
Unfortunately the same problem. It appears that something has changed on the AWS side indeed. It's like activating the function is too early. It only happens for me when I use the --activate parameter.

**Comment by aarondfrancis** [comment] 2022-01-02 17:25
Man, I cannot make this happen! @jeffreyvanhees @949mac what region are yall using?

I just tried us-east-1 and us-east-2 and both deployed just fine.

```
[Sidecar] Deploying App\Sidecar\OgImage2 to Lambda as `SC-Laravel-local-Sidecar-OgImage2`.
          ↳ Environment: local
          ↳ Package Type: Zip
          ↳ Runtime: nodejs12.x
          ↳ Creating new lambda function.
          ↳ Packaging files for deployment.
          ↳ Package unchanged. Reusing s3://sidecar-us-east-2-1622652312/sidecar/001-50927afdb583fd46fdbfb08ef1810cc1.zip.
[Sidecar] Activating function App\Sidecar\OgImage2.
          ↳ Environment variables not managed by Sidecar. Skipping.
          ↳ Creating alias for Version 1 of SC-Laravel-local-Sidecar-OgImage2.
```

**Comment by danatemple** [comment] 2022-01-02 17:46
us-east-1 - it happens "every now and again" .. 

Have you had a look at the AWS response attached above?

**Comment by aarondfrancis** [comment] 2022-01-02 22:02
Well I certainly didn't mean to auto-close this, ha.

But! I did add a "waiter" to wait until the function is in the proper state before trying to update it further. This _should_ be an airtight fix. The only other thing I can foresee is that we'll need to add the waiter in more places than it currently exists, but that *should* be easy.

A huge thank you to all of you for your patience and detective work, including reaching out to AWS @danatemple. I couldn't have figured this out without y'all.

I left these links in the source code, but here are some of the things that helped me along the way: 

- https://aws.amazon.com/de/blogs/compute/coming-soon-expansion-of-aws-lambda-states-to-all-functions/
- https://aws.amazon.com/blogs/compute/tracking-the-state-of-lambda-functions/
- https://github.com/hammerstonedev/sidecar/issues/32
- https://github.com/aws/aws-sdk-php/blob/master/src/data/lambda/2015-03-31/waiters-2.json
- https://github.com/claudiajs/claudia/pull/230/files
- https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/guide_waiters.html

I'm waiting for the tests to finish then I'll publish a new version and we can drive that one around for a while and see if it did indeed fix it. Fingers crossed.

**Comment by aarondfrancis** [comment] 2022-01-02 22:05
Published v0.3.4.

**Comment by danatemple** [comment] 2022-01-03 06:55
@aarondfrancis awesome, thanks for this fix! Have updated and tried a few deploys, no problems seen!

**Comment by 949mac** [comment] 2022-01-03 21:43
Awesome. Thank you so much. These bugs can be killer without reliable steps to reproduce. Great work.

**Comment by aarondfrancis** [comment] 2022-01-05 01:51
Optimistically closing this. Feel free to open a new issue or comment here again if y'all start to see these errors again!

**Closed by aarondfrancis** 2022-01-05 01:51 UTC
